---
title: "MCMC sensitivty analysis"
author: "Jackson Kwok"
date: "29/03/2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this article, we present a basic template for performing MCMC sensitivity analysis. 

## Data

```{r, echo=FALSE, eval=T, message=FALSE, warning=FALSE, fig.width=10, fig.height=4, fig.align='center'}
# Setup and Simulate time series data 
set.seed(234)
library(BayesSense)
num_data <- 365
dim_data <- 2
lag <- 2
converted_dim <- dim_data + dim_data^2 * lag
sim <- simulate_VAR(m = num_data, n = dim_data, p = lag, init_y_t = c(10, -10))
data0 <- sim$data
```

```{r, echo=FALSE, eval=T, message=FALSE, warning=FALSE, fig.width=10, fig.height=4, fig.align='center'}
# Plot and display data
library(plotly)
library(ggplot2)
data1 <- data.frame(cbind(1:nrow(data0), data0)) %>% 
  purrr::set_names(c("time", paste0("ts", 1:2)))

plot_ly(data1) %>% 
  add_lines(x = ~time, y = ~ts1, name = "time series 1") %>% 
  add_lines(x = ~time, y = ~ts2, name = "time series 2") %>% 
  layout(title = "Time series data", 
         xaxis = list(title = "Time (Day)"), 
         yaxis = list(title = "Index"))

DT::datatable(
  round(t(data1), 3), 
  colnames = "", 
  options=list(scrollX=TRUE)
)
sprintf("%d time series with %d datapoints each.", ncol(data1) - 1, nrow(data1))
```

## Model and Parameter estimates

Vector-Auto-Regressive (VAR) model. 

$$\vec{y_t} = \vec{b} + B_1 \vec{y_{t-1}} + ... + B_p \vec{y_{t-p}}+\vec{\epsilon_t}$$
where $\vec{\epsilon_t} \sim N(\vec{0}, \Sigma)$, $\Sigma$ is $n \times n$.

```{r}
init_b_0 <- rnorm(converted_dim)
init_B_0 <- prior_cov <- pdmatrix(converted_dim)$Sigma
init_v_0 <- dim_data
init_S_0 <- pdmatrix(dim_data)$Sigma
init_Sigma <- diag(dim_data)
num_steps <- 3e4
burn_ins <- 1e3
res <- VAR_AD(data0, lag = lag, 
       init_b_0, init_B_0, init_v_0, init_S_0, init_Sigma,
       num_steps, burn_ins)
save(res, "simulated_data_autodiff")
```








## Sensitivity Analysis and Convergence Diagnostic

### Sensitivity Analysis


### Convergence plot


## Forecast 
