# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kronecker_sp_3_cpp <- function(B, A) {
    .Call('_BayesSense_kronecker_sp_3_cpp', PACKAGE = 'BayesSense', B, A)
}

eigenMapMatMult <- function(A, B) {
    .Call('_BayesSense_eigenMapMatMult', PACKAGE = 'BayesSense', A, B)
}

